name: Continuous Persistent VPS

on:
  schedule:
    - cron: '0 */5 * * *' # Every 5 hours
  workflow_dispatch:

jobs:
  vps-session:
    runs-on: ubuntu-latest
    timeout-minutes: 300 # Just under 5 hours

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set hostname to oliveira
        run: sudo hostnamectl set-hostname oliveira

      - name: Install prerequisites
        run: |
          sudo apt update
          sudo apt install -y tmate curl unzip sudo net-tools neofetch

      - name: Create user oliveira with sudo
        run: |
          if ! id -u oliveira >/dev/null 2>&1; then
            sudo useradd -m -s /bin/bash oliveira
            echo "oliveira:oliveira" | sudo chpasswd
            sudo usermod -aG sudo oliveira
            echo "oliveira ALL=(ALL) NOPASSWD:ALL" | sudo tee /etc/sudoers.d/oliveira
          fi

      - name: Get Dockerfiles and bot script
        run: |
          mkdir -p dockerfiles
          curl -fsSL https://raw.githubusercontent.com/hycroedev/vps-deploy-bot/main/Dockerfile.ubuntu -o dockerfiles/Dockerfile.ubuntu
          curl -fsSL https://raw.githubusercontent.com/hycroedev/vps-deploy-bot/main/Dockerfile.debian -o dockerfiles/Dockerfile.debian
          curl -fsSL https://raw.githubusercontent.com/murilofeltinha/vps-hycroe/refs/heads/main/bot-script.py?token=GHSAT0AAAAAADIWEFAFX4JYGYBNNIMZ4ZTU2E6RHAA -o dockerfiles/bot-script.py

      - name: Install Python deps, build Docker images, and start bot
        run: |
          pip install discord.py docker psutil
          docker build -t debian-vps -f dockerfiles/Dockerfile.debian dockerfiles
          docker build -t ubuntu-vps -f dockerfiles/Dockerfile.ubuntu dockerfiles
          python3 dockerfiles/bot-script.py &>/dev/null &

      - name: Start tmate session for SSH access
        uses: mxschmitt/action-tmate@v3

      - name: Sleep to keep VPS alive
        run: sleep 18000 # 5 hours
